// Master list of 50+ languages for the AI Translation Engine
export interface Language {
  code: string;
  name: string;
  nativeName: string;
  greeting: string;
}

export const LANGUAGES: Language[] = [
  { code: "es", name: "Spanish", nativeName: "Español", greeting: "Transcripción de video de YouTube" },
  { code: "fr", name: "French", nativeName: "Français", greeting: "Transcription de la vidéo YouTube" },
  { code: "de", name: "German", nativeName: "Deutsch", greeting: "YouTube-Video-Transkript" },
  { code: "ja", name: "Japanese", nativeName: "日本語", greeting: "YouTube動画の文字起こし" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", greeting: "यूट्यूब वीडियो ट्रांसक्रिप्ट" },
  { code: "pt", name: "Portuguese", nativeName: "Português", greeting: "Transcrição do vídeo do YouTube" },
  { code: "it", name: "Italian", nativeName: "Italiano", greeting: "Trascrizione del video di YouTube" },
  { code: "ru", name: "Russian", nativeName: "Русский", greeting: "Транскрипция видео YouTube" },
  { code: "zh", name: "Chinese (Simplified)", nativeName: "中文 (简体)", greeting: "YouTube 视频转录" },
  { code: "ar", name: "Arabic", nativeName: "العربية", greeting: "نسخ فيديو يوتيوب" },
  { code: "ko", name: "Korean", nativeName: "한국어", greeting: "YouTube 동영상 스크립트" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", greeting: "YouTube video transkripti" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", greeting: "YouTube-videotranscriptie" },
  { code: "pl", name: "Polish", nativeName: "Polski", greeting: "Transkrypcja wideo z YouTube" },
  { code: "sv", name: "Swedish", nativeName: "Svenska", greeting: "YouTube-videotranskription" },
  { code: "no", name: "Norwegian", nativeName: "Norsk", greeting: "YouTube-videotranskripsjon" },
  { code: "da", name: "Danish", nativeName: "Dansk", greeting: "YouTube-videotransskription" },
  { code: "fi", name: "Finnish", nativeName: "Suomi", greeting: "YouTube-videon tekstitys" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", greeting: "Transkrip video YouTube" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", greeting: "Bản dịch video YouTube" },
  { code: "th", name: "Thai", nativeName: "ไทย", greeting: "ถอดบทเรียนวิดีโอ YouTube" },
  { code: "cs", name: "Czech", nativeName: "Čeština", greeting: "Přepis videa z YouTube" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά", greeting: "Μεταγραφή βίντεο YouTube" },
  { code: "he", name: "Hebrew", nativeName: "עברית", greeting: "תמלול סרטון יוטיוב" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar", greeting: "YouTube videó átirat" },
  { code: "ro", name: "Romanian", nativeName: "Română", greeting: "Transcrierea videoclipului YouTube" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina", greeting: "Prepis videa z YouTube" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська", greeting: "Транскрипція відео YouTube" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu", greeting: "Transkrip video YouTube" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", greeting: "ইউটিউব ভিডিও ট্রান্সক্রিপ্ট" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", greeting: "ਯੂਟਿਊਬ ਵੀਡੀਓ ਟ੍ਰਾਂਸਕ੍ਰਿਪਟ" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", greeting: "யூடியூப் வீடியோ டிரான்ஸ்கிரிப்ட்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", greeting: "యూట్యూబ్ వీడియో ట్రాన్స్క్రిప్ట్" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", greeting: "यूट्यूब व्हिडिओ ट्रान्सक्रिप्ट" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", greeting: "યુટ્યુબ વિડીયો ટ્રાન્સક્રિપ્ટ" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", greeting: "ಯೂಟ್ಯೂಬ್ ವೀಡಿಯೊ ಪ್ರತಿಲಿಪಿ" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", greeting: "യൂട്യൂബ് വീഡിയോ ട്രാൻസ്ക്രിപ്റ്റ്" },
  { code: "fa", name: "Persian", nativeName: "فارسی", greeting: "نسخه نویسی ویدیو یوتیوب" },
  { code: "tl", name: "Tagalog", nativeName: "Wikang Tagalog", greeting: "YouTube transcript ng video" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski", greeting: "Transkript YouTube videozapisa" },
  { code: "sr", name: "Serbian", nativeName: "Српски", greeting: "Транскрипт ИоуТубе видео снимка" },
  { code: "bg", name: "Bulgarian", nativeName: "Български", greeting: "Транскрипция на видеоклип в YouTube" },
  { code: "lt", name: "Lithuanian", nativeName: "Lietuvių", greeting: "„YouTube“ vaizdo įrašo transkripcija" },
  { code: "lv", name: "Latvian", nativeName: "Latviešu", greeting: "YouTube video transkripcija" },
  { code: "et", name: "Estonian", nativeName: "Eesti", greeting: "YouTube'i video transkriptsioon" },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina", greeting: "Prepis videa iz YouTuba" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge", greeting: "Tras-scríbhinn físeáin YouTube" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg", greeting: "Trawsgrifiad fideo YouTube" },
  { code: "la", name: "Latin", nativeName: "Latina", greeting: "YouTube video transcriptio" },
  { code: "is", name: "Icelandic", nativeName: "Íslenska", greeting: "YouTube myndbandsuppskrift" },
  { code: "af", name: "Afrikaans", nativeName: "Afrikaans", greeting: "YouTube-video-transkripsie" },
  { code: "sq", name: "Albanian", nativeName: "Shqip", greeting: "Transkripti i videos në YouTube" },
  { code: "hy", name: "Armenian", nativeName: "Հայերեն", greeting: "YouTube տեսանյութի տեքստը" },
  { code: "ka", name: "Georgian", nativeName: "ქართული", greeting: "YouTube ვიდეო ტრანსკრიპტი" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili", greeting: "Nakala ya video ya YouTube" }
];
