import React, { useState, useEffect } from "react";
import { 
  ArrowRight, Search, Sparkles, Check, Cpu, Copy, ExternalLink, 
  Shield, Zap, Terminal, FileText, Layout, MessageSquare, Play, 
  RefreshCw, CheckCircle2, FileJson, ArrowUpRight, HelpCircle
} from "lucide-react";

interface InteractiveDemoWidgetProps {
  theme: "light" | "dark";
  toolId: string;
  toolName: string;
}

export default function InteractiveDemoWidget({ theme, toolId, toolName }: InteractiveDemoWidgetProps) {
  const [demoStep, setDemoStep] = useState<number>(1);
  const [isSimulating, setIsSimulating] = useState<boolean>(false);
  const [simProgress, setSimProgress] = useState<number>(0);
  const [streamLines, setStreamLines] = useState<string[]>([]);
  const [selectedExportFormat, setSelectedExportFormat] = useState<"notion" | "chatgpt" | "obsidian" | "word">("notion");
  const [copiedText, setCopiedText] = useState<string | null>(null);

  // High-fidelity target copy templates based on long-tail intents
  const mockOutputs: Record<string, Record<string, string>> = {
    transcript: {
      notion: `# YouTube Transcript Notes\n\n**Video Title:** 10 Hidden YouTube SEO Tricks to Double CTR\n**Source URL:** https://youtube.com/watch?v=k1t6_nLhXw0\n\n## Core Transcript Outline\n- [00:15] The 2-Second Title Rule: Your first five words determine impressions.\n- [01:45] The CTR Loop Signal: Google tracks navigational queries.\n- [03:10] The Transcript Punctuation Secret: Why clean transcriptions score higher in search indexes.`,
      chatgpt: `Act as an expert YouTube Analyst. Analyze the following transcript from TranscriptG, and outline the 3 main strategies the creator used to double their CTR. Focus specifically on actionable tactics that require no budget:\n\n[00:15] Title Rule: "The absolute hook of any title is the brand footprint..."\n[01:45] CTR Loop: "If users search for your brand directly..."`,
      obsidian: `---\ntags: [youtube-learning, seo-hacks, transcriptg]\ncreated: 2026-07-13\n---\n\n# YouTube Video Notes: 10 Hidden SEO Tricks\n\n- **Anchor URL**: https://transcriptg.com/tools/transcript\n- **Key Takeaway**: Entity-based brand search overrides standard text keyword densities.`,
      word: `YOUTUBE VIDEO TRANSCRIPT FILE\nGenerated via TranscriptG (No Sign-Up Extractor)\n==================================================\n\n00:00:15 - Hey everyone, today we are breaking down the 10 hidden YouTube SEO tricks.\n00:01:45 - The brand search signal is the gold standard for video discovery indexes.`
    },
    summary: {
      notion: `# AI Video Summarizer Notes\n\n**Video Title:** Ultimate Productivity Blueprint\n\n## 💡 Executive Brief\nThis video details the three core psychological habits that prevent procrastination and maximize focus bandwidth.\n\n## 🔑 Key Takeaways\n- Focus blocks should be capped at 45 minutes.\n- Minimize task-switching costs by grouping administrative duties.\n- Clean workspaces reduce attention drift by up to 22%.`,
      chatgpt: `You are a professional copywriter. Here is the AI Video Summary generated by TranscriptG. Rewrite this into a high-converting weekly newsletter draft for absolute beginners:\n\n- Focus Blocks: 45 min focus caps\n- Task grouping: Reduces context drift\n- Minimalist setups: 22% less cognitive fatigue`,
      obsidian: `---\ntype: literature-note\nsource: YouTube Summary AI\n---\n\n# Summary: Ultimate Productivity Blueprint\n\n- [[Cognitive Bandwidth]]\n- [[Focus blocks]]\n- [[Task switching costs]]`,
      word: `AI VIDEO SUMMARY EXECUTIVE LOG\nGenerated via TranscriptG (Unlimited Summaries)\n==================================================\n\nTOPIC: Ultimate Productivity Blueprint\nSUMMARY: A complete system for cognitive load optimization.`
    },
    blog: {
      notion: `# SEO Ready Article Workspace\n\n**Working Title:** The Brand Search Signal Engine: Why Keyword SEO is a Trap\n\n## Introduction\nTraditional keyword stuffing is dead. Discover how modern algorithms prioritize brand navigational authority over raw text match tags...`,
      chatgpt: `I have a YouTube transcript. Rewrite this transcript into a highly optimized SEO blog post for Medium. Use subheaders, bullet lists, and natural integrations of the keyword 'Convert YouTube video to Notion notes':`,
      obsidian: `# Blog Draft: Why Keyword SEO is a Trap\n\n- Category: Digital Marketing\n- Source Video: https://transcriptg.com/tools/blog`,
      word: `SEO BLOG ARTICLE DRAFT\nGenerated via TranscriptG (YouTube to Blog Generator)\n==================================================\n\nTITLE: The Brand Search Signal Engine: Why Keyword SEO is a Trap`
    }
  };

  const currentToolOutputs = mockOutputs[toolId] || mockOutputs["transcript"];

  // Run the 10-second interactive simulator sequence
  useEffect(() => {
    let timer: NodeJS.Timeout;
    if (isSimulating) {
      setDemoStep(2);
      setSimProgress(0);
      setStreamLines([]);
      
      const interval = setInterval(() => {
        setSimProgress((prev) => {
          const next = prev + 10;
          if (next >= 100) {
            clearInterval(interval);
            setIsSimulating(false);
            setDemoStep(3);
            startStreamingOutput();
            return 100;
          }
          return next;
        });
      }, 350); // Total ~3.5 seconds simulation sequence
      
      return () => clearInterval(interval);
    }
  }, [isSimulating]);

  const startStreamingOutput = () => {
    const rawLines = [
      "⚡ [0.5s] Establishing browser handshake with oEmbed metadata arrays...",
      "🛡️ [1.2s] Parsing audio timelines locally inside client sandbox...",
      "🧠 [2.0s] Gemini AI Engine activated: Refining punctuation structures...",
      "📁 [3.1s] Restoring timelines & clickable timestamp anchors...",
      "✅ [3.8s] Analysis complete! Formatting outputs for Notion & ChatGPT..."
    ];
    
    let currentLine = 0;
    const interval = setInterval(() => {
      if (currentLine < rawLines.length) {
        setStreamLines((prev) => [...prev, rawLines[currentLine]]);
        currentLine++;
      } else {
        clearInterval(interval);
        setDemoStep(4);
      }
    }, 900);
  };

  const handleTriggerSimulation = () => {
    setIsSimulating(true);
  };

  const handleCopyText = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedText("Copied successfully!");
    setTimeout(() => setCopiedText(null), 2500);
  };

  return (
    <div className="space-y-10" id="interactive-demo-widget-container">
      
      {/* VISUAL STEP-BY-STEP GRAPHIC */}
      <div className={`p-6 rounded-2xl border ${
        theme === "dark" ? "bg-slate-900/40 border-slate-800" : "bg-white border-slate-200/80 shadow-md"
      }`}>
        <h3 className="text-sm font-bold uppercase tracking-wider mb-6 flex items-center gap-2">
          <LayersIcon className="w-4.5 h-4.5 text-red-500 animate-pulse" />
          <span>The TranscriptG Fast Pipeline: How It Works</span>
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 relative">
          {/* Decorative connector lines on desktop */}
          <div className="hidden md:block absolute top-[28px] left-[12%] right-[12%] h-0.5 bg-gradient-to-r from-red-500/20 via-rose-500/20 to-emerald-500/20 z-0"></div>

          {/* Step 1 */}
          <div className="flex flex-col items-center text-center relative z-10 space-y-3">
            <div className={`w-14 h-14 rounded-full flex items-center justify-center font-bold text-sm border-2 transition-all duration-300 ${
              demoStep >= 1 
                ? "bg-red-500/10 border-red-500 text-red-500 shadow-md shadow-red-500/5" 
                : "bg-slate-900/20 border-slate-800 text-slate-500"
            }`}>
              <Search className="w-5.5 h-5.5" />
            </div>
            <div>
              <p className="font-extrabold text-xs">1. Paste Video URL</p>
              <p className={`text-[10px] mt-0.5 ${theme === "dark" ? "text-slate-400" : "text-slate-500"}`}>
                Drop any public YouTube link. No credentials or login needed.
              </p>
            </div>
          </div>

          {/* Step 2 */}
          <div className="flex flex-col items-center text-center relative z-10 space-y-3">
            <div className={`w-14 h-14 rounded-full flex items-center justify-center font-bold text-sm border-2 transition-all duration-300 ${
              demoStep >= 2 
                ? "bg-rose-500/10 border-rose-500 text-rose-500 shadow-md shadow-rose-500/5" 
                : "bg-slate-900/20 border-slate-800 text-slate-500"
            }`}>
              <Cpu className="w-5.5 h-5.5" />
            </div>
            <div>
              <p className="font-extrabold text-xs">2. In-Browser AI Parse</p>
              <p className={`text-[10px] mt-0.5 ${theme === "dark" ? "text-slate-400" : "text-slate-500"}`}>
                Gemini structures transcript layout with millisecond-exact precision.
              </p>
            </div>
          </div>

          {/* Step 3 */}
          <div className="flex flex-col items-center text-center relative z-10 space-y-3">
            <div className={`w-14 h-14 rounded-full flex items-center justify-center font-bold text-sm border-2 transition-all duration-300 ${
              demoStep >= 3 
                ? "bg-amber-500/10 border-amber-500 text-amber-500 shadow-md shadow-amber-500/5" 
                : "bg-slate-900/20 border-slate-800 text-slate-500"
            }`}>
              <FileText className="w-5.5 h-5.5" />
            </div>
            <div>
              <p className="font-extrabold text-xs">3. Long-Tail Optimization</p>
              <p className={`text-[10px] mt-0.5 ${theme === "dark" ? "text-slate-400" : "text-slate-500"}`}>
                Optimized perfectly for ChatGPT prompts and Notion notes templates.
              </p>
            </div>
          </div>

          {/* Step 4 */}
          <div className="flex flex-col items-center text-center relative z-10 space-y-3">
            <div className={`w-14 h-14 rounded-full flex items-center justify-center font-bold text-sm border-2 transition-all duration-300 ${
              demoStep >= 4 
                ? "bg-emerald-500/10 border-emerald-500 text-emerald-500 shadow-md shadow-emerald-500/5" 
                : "bg-slate-900/20 border-slate-800 text-slate-500"
            }`}>
              <CheckCircle2 className="w-5.5 h-5.5" />
            </div>
            <div>
              <p className="font-extrabold text-xs">4. Unlimited Free Export</p>
              <p className={`text-[10px] mt-0.5 ${theme === "dark" ? "text-slate-400" : "text-slate-500"}`}>
                Click export to save straight to Obsidian, Notion, or text files.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* 10-SECOND INTERACTIVE SIMULATOR WIDGET */}
      <div className={`rounded-3xl border overflow-hidden ${
        theme === "dark" ? "bg-slate-950 border-slate-850" : "bg-white border-slate-200/90 shadow-lg"
      }`}>
        {/* Simulator Bar Head */}
        <div className={`px-6 py-4 border-b flex items-center justify-between ${
          theme === "dark" ? "bg-slate-900/50 border-slate-800" : "bg-gray-50 border-slate-100"
        }`}>
          <div className="flex items-center gap-2">
            <span className="w-3 h-3 rounded-full bg-red-500"></span>
            <span className="w-3 h-3 rounded-full bg-amber-400"></span>
            <span className="w-3 h-3 rounded-full bg-emerald-400"></span>
            <span className={`text-[10px] font-mono font-bold tracking-wider ml-2 ${theme === "dark" ? "text-slate-400" : "text-slate-500"}`}>
              LIVE DEMO SIMULATOR • {toolName.toUpperCase()}
            </span>
          </div>
          <div className="flex items-center gap-1.5 px-2.5 py-1 rounded bg-red-500/10 border border-red-500/15">
            <Zap className="w-3 h-3 text-red-500 animate-pulse" />
            <span className="text-[9px] font-bold text-red-400 uppercase tracking-widest">Instant Play</span>
          </div>
        </div>

        {/* Simulator Body */}
        <div className="p-6 sm:p-8 space-y-6">
          
          {/* SIMULATOR PHASE 1: INPUT SIMULATION */}
          {demoStep === 1 && (
            <div className="space-y-6 max-w-xl mx-auto text-center py-6 animate-fadeIn">
              <div className="inline-flex items-center justify-center w-14 h-14 rounded-full bg-red-500/10 text-red-500 mb-2">
                <Play className="w-6 h-6 animate-bounce" />
              </div>
              <div>
                <h4 className="text-base font-bold">Launch a 10-Second Interactive Simulation</h4>
                <p className={`text-xs mt-1 ${theme === "dark" ? "text-slate-400" : "text-slate-500"}`}>
                  Experience the ultra-fast pipeline of TranscriptG without leaving this page. Click below to simulate converting a high-CTR SEO video to Notion notes & ChatGPT.
                </p>
              </div>

              {/* Sample Simulated URL bar */}
              <div className={`p-3 rounded-xl border flex items-center justify-between gap-3 text-left ${
                theme === "dark" ? "bg-slate-900/80 border-slate-800" : "bg-gray-50 border-slate-200"
              }`}>
                <div className="flex items-center gap-2 min-w-0">
                  <span className="text-xs font-bold text-slate-500 shrink-0">URL:</span>
                  <span className="text-xs font-mono text-red-500 truncate font-semibold">https://www.youtube.com/watch?v=k1t6_nLhXw0</span>
                </div>
                <span className="text-[10px] bg-slate-800/80 text-slate-400 px-2 py-0.5 rounded font-bold shrink-0">
                  Sample Video
                </span>
              </div>

              <button
                onClick={handleTriggerSimulation}
                className="w-full py-3.5 bg-gradient-to-r from-red-500 via-rose-500 to-amber-500 hover:from-red-600 hover:to-amber-600 text-white font-extrabold text-sm rounded-xl transition-all shadow-md shadow-red-500/15"
              >
                Start Fast Demo Simulation (3 Seconds)
              </button>
            </div>
          )}

          {/* SIMULATOR PHASE 2: PROCESSING RUN */}
          {demoStep === 2 && (
            <div className="space-y-6 py-8 text-center animate-fadeIn">
              <div className="flex justify-center">
                <RefreshCw className="w-10 h-10 text-red-500 animate-spin" />
              </div>
              <div className="space-y-2 max-w-md mx-auto">
                <h4 className="text-sm font-bold uppercase tracking-wider">Compiling Core Client Workspace</h4>
                <p className={`text-xs ${theme === "dark" ? "text-slate-400" : "text-slate-500"}`}>
                  TranscriptG runs entirely client-side. No API keys are requested. Zero sign-up required.
                </p>
              </div>

              {/* simulated progress bar */}
              <div className="max-w-md mx-auto">
                <div className="flex items-center justify-between mb-2 text-xs font-mono font-bold">
                  <span>ANALYZING AUDIO CODES...</span>
                  <span>{simProgress}%</span>
                </div>
                <div className="w-full h-2 bg-slate-900 rounded-full overflow-hidden border border-slate-800">
                  <div 
                    className="h-full bg-gradient-to-r from-red-500 via-rose-500 to-amber-500 transition-all duration-300"
                    style={{ width: `${simProgress}%` }}
                  ></div>
                </div>
              </div>
            </div>
          )}

          {/* SIMULATOR PHASE 3: STREAMING LINES */}
          {demoStep === 3 && (
            <div className="space-y-4 py-4 animate-fadeIn">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-red-500 flex items-center gap-1.5">
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                  <span>STREAMING HIGH-FIDELITY CHUNKS</span>
                </span>
                <span className="text-[10px] font-mono text-slate-500">CLIENT COMPILER OK</span>
              </div>

              {/* Console log box */}
              <div className="p-5 rounded-2xl bg-slate-950 border border-slate-850 font-mono text-xs text-left h-44 overflow-y-auto space-y-2.5">
                {streamLines.map((line, idx) => (
                  <div key={idx} className="text-slate-300 flex items-start gap-2">
                    <span className="text-red-500 shrink-0">&gt;</span>
                    <span>{line}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* SIMULATOR PHASE 4: THE COMPLETED CONSOLE EXPORT WORKSPACE */}
          {demoStep === 4 && (
            <div className="space-y-6 animate-fadeIn text-left">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-xl bg-emerald-500/5 border border-emerald-500/10">
                <div className="flex items-start gap-2.5">
                  <CheckCircle2 className="w-5.5 h-5.5 text-emerald-500 shrink-0 mt-0.5" />
                  <div>
                    <h5 className="text-sm font-bold text-emerald-500">Analysis Succeeded!</h5>
                    <p className={`text-xs ${theme === "dark" ? "text-slate-400" : "text-slate-650"}`}>
                      Optimized for transactional search intent. Directly convert and import video data into Notion, ChatGPT, and Obsidian without limits.
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => {
                    setDemoStep(1);
                    setSimProgress(0);
                    setStreamLines([]);
                  }}
                  className={`px-3 py-1.5 rounded-lg font-bold text-[10px] uppercase border tracking-wider shrink-0 text-center transition-all ${
                    theme === "dark" 
                      ? "border-slate-800 bg-slate-900 text-slate-300 hover:bg-slate-800" 
                      : "border-slate-200 bg-white text-slate-700 hover:bg-gray-50 shadow-sm"
                  }`}
                >
                  Reset Demo
                </button>
              </div>

              {/* Export Selector Tab Layout */}
              <div className="space-y-3">
                <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block">
                  Select Destination (Auto-Optimized Templates)
                </label>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
                  <button
                    onClick={() => setSelectedExportFormat("notion")}
                    className={`py-2 text-xs font-bold rounded-xl border flex items-center justify-center gap-2 transition-all ${
                      selectedExportFormat === "notion"
                        ? "bg-red-500 border-red-500 text-white shadow-md shadow-red-500/10"
                        : theme === "dark"
                          ? "border-slate-800 bg-slate-900/50 text-slate-400 hover:bg-slate-800"
                          : "border-slate-200 bg-white text-slate-600 hover:bg-gray-50"
                    }`}
                  >
                    <Layout className="w-3.5 h-3.5" />
                    <span>Notion Notes</span>
                  </button>

                  <button
                    onClick={() => setSelectedExportFormat("chatgpt")}
                    className={`py-2 text-xs font-bold rounded-xl border flex items-center justify-center gap-2 transition-all ${
                      selectedExportFormat === "chatgpt"
                        ? "bg-red-500 border-red-500 text-white shadow-md shadow-red-500/10"
                        : theme === "dark"
                          ? "border-slate-800 bg-slate-900/50 text-slate-400 hover:bg-slate-800"
                          : "border-slate-200 bg-white text-slate-600 hover:bg-gray-50"
                    }`}
                  >
                    <MessageSquare className="w-3.5 h-3.5" />
                    <span>ChatGPT Prompt</span>
                  </button>

                  <button
                    onClick={() => setSelectedExportFormat("obsidian")}
                    className={`py-2 text-xs font-bold rounded-xl border flex items-center justify-center gap-2 transition-all ${
                      selectedExportFormat === "obsidian"
                        ? "bg-red-500 border-red-500 text-white shadow-md shadow-red-500/10"
                        : theme === "dark"
                          ? "border-slate-800 bg-slate-900/50 text-slate-400 hover:bg-slate-800"
                          : "border-slate-200 bg-white text-slate-600 hover:bg-gray-50"
                    }`}
                  >
                    <FileJson className="w-3.5 h-3.5" />
                    <span>Obsidian Vault</span>
                  </button>

                  <button
                    onClick={() => setSelectedExportFormat("word")}
                    className={`py-2 text-xs font-bold rounded-xl border flex items-center justify-center gap-2 transition-all ${
                      selectedExportFormat === "word"
                        ? "bg-red-500 border-red-500 text-white shadow-md shadow-red-500/10"
                        : theme === "dark"
                          ? "border-slate-800 bg-slate-900/50 text-slate-400 hover:bg-slate-800"
                          : "border-slate-200 bg-white text-slate-600 hover:bg-gray-50"
                    }`}
                  >
                    <FileText className="w-3.5 h-3.5" />
                    <span>Word/SRT Subtitles</span>
                  </button>
                </div>
              </div>

              {/* Simulated Output Editor Display */}
              <div className="relative">
                <div className="absolute top-3 right-3 z-10 flex items-center gap-2">
                  <button
                    onClick={() => handleCopyText(currentToolOutputs[selectedExportFormat] || "")}
                    className={`p-2 rounded-lg border flex items-center gap-1.5 text-[10px] font-bold uppercase transition-all ${
                      theme === "dark"
                        ? "bg-slate-900 border-slate-800 text-slate-300 hover:bg-slate-800"
                        : "bg-white border-slate-200 text-slate-700 hover:bg-gray-50 shadow-sm"
                    }`}
                  >
                    <Copy className="w-3.5 h-3.5 text-red-500" />
                    <span>Copy Draft</span>
                  </button>
                </div>

                {copiedText && (
                  <div className="absolute bottom-3 right-3 z-20 px-3 py-1.5 bg-emerald-500 text-white font-extrabold text-[10px] rounded-lg shadow-lg animate-bounce">
                    {copiedText}
                  </div>
                )}

                <pre className={`p-5 rounded-2xl border font-mono text-xs overflow-x-auto h-52 leading-relaxed whitespace-pre-wrap ${
                  theme === "dark" 
                    ? "bg-slate-900/60 border-slate-800 text-slate-300" 
                    : "bg-gray-50 border-slate-200 text-slate-800 shadow-inner"
                }`}>
                  {currentToolOutputs[selectedExportFormat] || ""}
                </pre>
              </div>

              <div className="text-center">
                <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest block mb-1">
                  READY TO TEST IT OUT FOR REAL?
                </span>
                <p className={`text-xs ${theme === "dark" ? "text-slate-400" : "text-slate-600"}`}>
                  Scroll down to the <strong>Interactive Playground</strong> below to paste any live YouTube URL or test one of our precompiled high-fidelity demos!
                </p>
              </div>
            </div>
          )}

        </div>
      </div>

    </div>
  );
}

// Simple fallback wrappers for custom SVG indicators without using heavy libraries
function LayersIcon({ className }: { className?: string }) {
  return (
    <svg 
      className={className} 
      xmlns="http://www.w3.org/2000/svg" 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth="2.5" 
      strokeLinecap="round" 
      strokeLinejoin="round"
    >
      <path d="m12 3-10 5 10 5 10-5-10-5Z" />
      <path d="m2 17 10 5 10-5" />
      <path d="m2 12 10 5 10-5" />
    </svg>
  );
}
